site_name: André Mattos
site_url: "https://andrematte.github.io"
site_description: "Website de André Mattos"
repo_url: "https://github.com/andrematte/andrematte.github.io"
repo_name: "andrematte/andrematte.github.io"
edit_uri: "tree/main/docs"

theme:
  name: material
  language: en
  custom_dir: overrides
  favicon: assets/favicon.png

  icon:
    repo: material/github
    logo: material/robot-happy

  font:
    text: Lato
    code: JetBrains Mono

  features:
    # - navigation.focus
    # - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue grey
      accent: #2E6CCC
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue grey
      accent: #2E6CCC

plugins:
  - search
  - privacy
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pt
          name: Português
          build: true

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  cli: "cd ~/andrematte"
  generator: false
  subtitle: "PhD Candidate @ Universidade Federal do Pará"
  subtitle_pt: "Doutorando @ Universidade Federal do Pará"
  bio: Machine Learning | Computer Vision | Data Analysis
  bio_pt: Aprendizado de Máquina | Visão Computacional | Análise de Dados
  # avatar: assets/avatar.png
  avatar: https://github.com/andrematte.png
  socials:
    - github: https://github.com/andrematte
    - linkedin: https://linkedin.com/in/andrematte
    # - website: https://andrematte.github.io
    - lattes: http://lattes.cnpq.br/5642339206700236
    - email: mailto:carlos.mattos@itec.ufpa.br
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/andrematte
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/andrematte
    - icon: fontawesome/solid/user-graduate
      link: http://lattes.cnpq.br/5642339206700236
    - icon: fontawesome/solid/envelope
      link: mailto:carlos.mattos@itec.ufpa.br

# nav:
#   - Home: index.md
#   - About Me: about.md
#   - Projects: projects.md


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js